In [1]:
import pandas as pd
import numpy as np

In [2]:
data_df = pd.read_csv('C:/Users/chanyoung/Desktop/RBFfitting/data/nonlinear15/non_linear15.csv')

In [3]:
data_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,1.361462,0.868128,1.119836,0.770762,1.543228,-0.484979,1.202227,1.812575,-1.328527,-0.452863,1.329738,1.401647,0.991044,-0.811218,1.467842
1,1.575887,0.502778,1.091785,0.330353,1.899189,-0.116958,0.987593,1.239788,-1.252347,-1.719436,0.306399,0.155447,1.327731,-1.011604,0.255159
2,1.333128,0.269990,1.162955,0.159699,1.646715,1.511054,1.234128,1.932573,-1.371554,-0.929414,0.733253,-1.374973,1.109616,-0.876114,0.516849
3,1.546209,0.297732,1.116530,0.482296,1.882979,-0.754731,0.762650,0.752762,-1.433568,-1.254173,1.054452,0.357797,1.062463,-0.555984,0.641373
4,1.661727,0.587748,1.013359,0.635559,1.464764,-0.546585,1.445773,1.857547,-1.568815,-0.723346,1.086332,1.656669,1.188205,-1.103284,1.055944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-2.679979,-1.521583,0.961226,1.383197,-1.392430,-0.701504,-1.148679,0.558870,-0.177923,0.470893,0.907261,0.241810,-0.787315,-1.079895,1.162237
96,-1.977749,-1.478321,1.206590,0.352901,-0.829146,2.016453,-0.940043,-1.517751,-0.011627,-0.044789,0.697491,1.705942,-1.024586,-0.860960,0.453126
97,-2.235777,-1.149230,1.102117,0.655368,-1.112439,1.523969,-0.893636,-1.060217,0.021164,0.303327,1.165866,0.894137,-0.852924,-0.960449,0.966107
98,-2.246968,-0.699402,1.122137,0.350573,-1.382963,-0.901993,-0.138510,0.038130,-0.155820,0.145202,0.447543,0.029613,-0.210601,-1.063089,-0.596316
99,-1.995263,-1.034104,1.198406,-0.165868,-1.343177,1.984393,-0.326622,0.359332,-0.523444,-1.098315,-0.004930,1.727443,-0.617220,-1.105536,-1.851388

In [5]:
from scipy import interpolate
import matplotlib.pyplot as plt

In [6]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.5)
    f_quadr = interpolate.interp1d(x, y, kind='quadratic')
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)

In [7]:
new_df.to_csv('./data/poly_nonlinear_200.csv', index = False)

In [8]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.25)
    f_quadr = interpolate.interp1d(x, y, kind='quadratic')
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)

In [9]:
new_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,1.361462,0.868128,1.119836,0.770762,1.543228,-0.484979,1.202227,1.812575,-1.328527,-0.452863,1.329738,1.401647,0.991044,-0.811218,1.467842
1,1.474075,0.765942,1.100030,0.641518,1.710691,-0.611214,1.080049,1.486883,-1.286381,-1.020400,0.913766,1.182238,1.138639,-0.891514,0.999162
2,1.547350,0.670989,1.088753,0.525035,1.825839,-0.591955,1.003550,1.282854,-1.259635,-1.420675,0.604553,0.901401,1.243952,-0.951677,0.640821
3,1.581288,0.583267,1.086005,0.421313,1.888671,-0.427203,0.972732,1.200489,-1.248291,-1.653687,0.402097,0.559138,1.306983,-0.991707,0.392820
4,1.575887,0.502778,1.091785,0.330353,1.899189,-0.116958,0.987593,1.239788,-1.252347,-1.719436,0.306399,0.155447,1.327731,-1.011604,0.255159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,-2.276089,-0.762163,1.107088,0.468986,-1.341846,-0.612888,-0.287935,-0.187510,-0.093093,0.278802,0.649885,0.062078,-0.313094,-1.043701,-0.153513
392,-2.246968,-0.699402,1.122137,0.350573,-1.382963,-0.901993,-0.138510,0.038130,-0.155820,0.145202,0.447543,0.029613,-0.210601,-1.063089,-0.596316
393,-2.204325,-0.695215,1.138793,0.227881,-1.403654,-0.786817,-0.067666,0.205633,-0.230218,-0.059310,0.280891,0.179916,-0.189768,-1.078967,-0.987505
394,-2.148160,-0.749604,1.157057,0.100911,-1.403920,-0.267361,-0.075404,0.315002,-0.316288,-0.334733,0.149927,0.512989,-0.250593,-1.091334,-1.327080
395,-2.078473,-0.862567,1.176928,-0.030339,-1.383761,0.656376,-0.161722,0.366235,-0.414030,-0.681068,0.054654,1.028831,-0.393077,-1.100190,-1.615041

In [10]:
new_df.to_csv('./data/poly_nonlinear_400.csv', index = False)

In [11]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.1)
    f_quadr = interpolate.interp1d(x, y, kind='quadratic')
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)
new_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,1.361462,0.868128,1.119836,0.770762,1.543228,-0.484979,1.202227,1.812575,-1.328527,-0.452863,1.329738,1.401647,0.991044,-0.811218,1.467842
1,1.411228,0.826386,1.110890,0.717533,1.616491,-0.552932,1.147874,1.667699,-1.309820,-0.699950,1.150538,1.321254,1.055156,-0.845752,1.267129
2,1.454699,0.785801,1.103309,0.666346,1.681384,-0.597606,1.100830,1.542288,-1.293578,-0.920274,0.988420,1.231034,1.112502,-0.877065,1.084071
3,1.491877,0.746373,1.097092,0.617200,1.737906,-0.619002,1.061095,1.436344,-1.279799,-1.113836,0.843383,1.130985,1.163084,-0.905157,0.918666
4,1.522761,0.708102,1.092240,0.570097,1.786058,-0.617118,1.028668,1.349866,-1.268485,-1.280637,0.715427,1.021107,1.206900,-0.930028,0.770916
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,-2.148160,-0.749604,1.157057,0.100911,-1.403920,-0.267361,-0.075404,0.315002,-0.316288,-0.334733,0.149927,0.512989,-0.250593,-1.091334,-1.327080
986,-2.121908,-0.787760,1.164813,0.048924,-1.398308,0.053620,-0.100501,0.342471,-0.353985,-0.464758,0.107535,0.697394,-0.297787,-1.095298,-1.448458
987,-2.093492,-0.835288,1.172825,-0.003747,-1.389427,0.439286,-0.138172,0.360639,-0.393548,-0.606128,0.070853,0.911041,-0.358047,-1.098700,-1.561578
988,-2.062912,-0.892188,1.181095,-0.057103,-1.377278,0.889637,-0.188416,0.369505,-0.434979,-0.758845,0.039882,1.153932,-0.431373,-1.101540,-1.666440
989,-2.030170,-0.958460,1.189622,-0.111143,-1.361862,1.404672,-0.251233,0.369069,-0.478278,-0.922907,0.014621,1.426066,-0.517763,-1.103819,-1.763043

In [12]:
new_df.to_csv('./data/poly_nonlinear_1000.csv', index = False)

In [13]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.5)
    f_quadr = interpolate.BSpline(x, y, k=2)
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)

In [14]:
new_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,0.125456,1.681278,1.360354,1.970887,-0.207581,1.482972,2.446518,5.202901,-1.833570,5.560184,5.765134,2.702507,-0.623593,0.161115,6.235613
1,0.632704,1.382611,1.259511,1.514646,0.502779,0.564490,1.935677,3.809132,-1.624517,3.127378,3.984545,2.328099,0.030203,-0.232970,4.339195
2,1.025657,1.117085,1.183472,1.125844,1.061031,-0.038994,1.540129,2.731755,-1.464310,1.208720,2.566504,1.882637,0.545299,-0.543086,2.811370
3,1.304314,0.884699,1.132239,0.804481,1.467174,-0.327480,1.259873,1.970772,-1.352950,-0.195789,1.511012,1.366119,0.921693,-0.769233,1.652139
4,1.468674,0.685453,1.105811,0.550557,1.721208,-0.300969,1.094910,1.526182,-1.290437,-1.086149,0.818068,0.778547,1.159388,-0.911411,0.861501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,-2.511467,-1.455419,1.019239,1.168224,-1.299457,-0.104534,-1.071762,0.160195,-0.169261,0.364508,0.939580,0.428923,-0.838218,-1.009097,1.029292
194,-2.328864,-1.499952,1.083908,0.868049,-1.110788,0.657474,-1.044361,-0.479441,-0.094775,0.213052,0.802376,0.973876,-0.905951,-0.970427,0.807682
195,-1.809237,-1.412157,1.264603,0.137928,-0.736173,2.613422,-0.863126,-1.916426,-0.002965,-0.151174,0.729810,1.893055,-1.075488,-0.790162,0.320181
196,-0.952586,-1.192034,1.561325,-1.022140,-0.175612,5.763308,-0.528055,-4.150759,0.106170,-0.728168,0.721881,3.186460,-1.346831,-0.468301,-0.433210
197,0.241089,-0.839583,1.974075,-2.612154,0.570896,10.107132,-0.039149,-7.182441,0.232630,-1.517932,0.778590,4.854092,-1.719977,-0.004844,-1.452491