In [1]:
import pandas as pd
import numpy as np

In [2]:
data_df = pd.read_csv('C:/Users/chanyoung/Desktop/RBFfitting/data/linear_SEM/linear_random_15.csv')

In [3]:
data_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.394290,0.346584,2.283581,-1.559172,0.641352,-2.573262,-0.407517,2.417698,-1.459789,3.592460,-4.019680,0.790601,-1.833108,3.480442,6.263829
1,1.442065,1.753741,-0.565542,-0.019844,-0.217345,-0.505208,-0.836395,3.096807,0.408895,-0.085744,-0.584852,-2.247291,0.499501,-1.568848,-1.472852
2,0.158795,-2.018488,1.363381,0.369942,-0.553480,-0.829095,0.797979,-0.601401,3.293327,-1.130796,2.697072,-1.542107,5.722812,-1.352311,-10.048166
3,1.180820,-0.302838,2.811929,-1.769756,1.171722,-4.010535,-0.339541,0.686395,-2.497994,-1.055499,-0.307648,-3.129533,2.950652,1.869410,1.805169
4,-0.535161,-1.304216,0.194147,-0.127602,-0.704615,1.089379,-0.192465,-2.312792,1.273764,1.341614,0.833310,0.889260,0.310092,-0.762782,-5.504899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-0.840972,0.419546,-0.149228,-2.066541,-1.074929,-2.850332,0.213039,-0.793650,1.961616,-0.598479,2.261300,-1.971938,4.682809,-3.231114,-8.642133
96,1.944198,-0.182270,2.034609,-1.864585,2.520702,-3.416261,-1.658307,2.704336,-2.603829,0.000127,0.012510,-3.950297,2.483015,-2.110721,-1.172979
97,-0.344352,0.441910,-0.655871,0.063072,-1.891197,-0.224493,-1.741030,0.773491,2.123364,1.707830,-3.144857,1.326751,-2.125668,0.281651,-1.305697
98,2.452951,-0.174916,1.877249,-0.442922,0.942239,-1.480626,-0.138366,2.849003,0.308466,-0.692214,0.693084,-3.875676,2.494982,-0.641738,-2.852213
99,-2.537599,0.363991,-4.153302,1.784039,-2.676023,4.545978,0.123587,-0.901131,2.163326,-2.637138,-0.808724,1.085521,1.152798,-2.617679,-5.516696

In [4]:
from scipy import interpolate
import matplotlib.pyplot as plt

In [5]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.5)
    f_quadr = interpolate.interp1d(x, y, kind='quadratic')
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.394290,0.346584,2.283581,-1.559172,0.641352,-2.573262,-0.407517,2.417698,-1.459789,3.592460,-4.019680,0.790601,-1.833108,3.480442,6.263829
1,1.329730,1.960005,0.164313,-0.699265,0.202877,-1.298544,-1.000261,3.546417,-0.936816,1.382473,-2.458052,-1.361308,-1.293288,0.288378,3.125299
2,1.442065,1.753741,-0.565542,-0.019844,-0.217345,-0.505208,-0.836395,3.096807,0.408895,-0.085744,-0.584852,-2.247291,0.499501,-1.568848,-1.472852
3,0.731297,-0.272207,0.094016,0.479093,-0.619314,-0.193253,0.084081,1.068868,2.577343,-0.812191,1.599919,-1.867348,3.545260,-2.091234,-7.530623
4,0.158795,-2.018488,1.363381,0.369942,-0.553480,-0.829095,0.797979,-0.601401,3.293327,-1.130796,2.697072,-1.542107,5.722812,-1.352311,-10.048166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,0.750667,0.151454,0.558994,-0.804000,0.316036,-1.650150,-1.969554,1.830668,-0.452951,1.088466,-2.077572,-0.966614,-0.422215,-0.813882,-0.542397
194,-0.344352,0.441910,-0.655871,0.063072,-1.891197,-0.224493,-1.741030,0.773491,2.123364,1.707830,-3.144857,1.326751,-2.125668,0.281651,-1.305697
195,1.072349,0.171195,0.676536,-0.153028,-0.734488,-0.918534,-0.961916,1.784238,1.614829,0.802104,-1.438770,-1.008574,-0.172902,0.156676,-2.011435
196,2.452951,-0.174916,1.877249,-0.442922,0.942239,-1.480626,-0.138366,2.849003,0.308466,-0.692214,0.693084,-3.875676,2.494982,-0.641738,-2.852213
197,1.249635,-0.110651,0.267303,0.202767,0.295060,0.340878,0.223469,1.953880,0.491298,-1.838628,0.903099,-3.177644,2.936882,-1.566523,-4.020634

In [6]:
new_df.to_csv('./data/poly_linear_200.csv', index = False)

In [7]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.25)
    f_quadr = interpolate.interp1d(x, y, kind='quadratic')
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)

In [8]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.394290,0.346584,2.283581,-1.559172,0.641352,-2.573262,-0.407517,2.417698,-1.459789,3.592460,-4.019680,0.790601,-1.833108,3.480442,6.263829
1,0.964898,1.380755,1.050271,-1.106658,0.419833,-1.875731,-0.798465,3.179349,-1.301145,2.394745,-3.277812,-0.443594,-1.719819,1.717555,4.877017
2,1.329730,1.960005,0.164313,-0.699265,0.202877,-1.298544,-1.000261,3.546417,-0.936816,1.382473,-2.458052,-1.361308,-1.293288,0.288378,3.125299
3,1.488786,2.084334,-0.374291,-0.336994,-0.009515,-0.841704,-1.012904,3.518903,-0.366803,0.555643,-1.560399,-1.962540,-0.553515,-0.807090,1.008676
4,1.442065,1.753741,-0.565542,-0.019844,-0.217345,-0.505208,-0.836395,3.096807,0.408895,-0.085744,-0.584852,-2.247291,0.499501,-1.568848,-1.472852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,2.085640,-0.053157,1.628225,-0.414922,0.394364,-1.497529,-0.492426,2.561607,0.775498,0.011457,-0.132613,-2.887766,1.439288,-0.226735,-2.390869
392,2.452951,-0.174916,1.877249,-0.442922,0.942239,-1.480626,-0.138366,2.849003,0.308466,-0.692214,0.693084,-3.875676,2.494982,-0.641738,-2.852213
393,2.174283,-0.194080,1.423608,-0.237025,0.909138,-0.867824,0.100266,2.646428,0.213733,-1.308909,1.038321,-3.972301,2.994180,-1.088334,-3.395468
394,1.249635,-0.110651,0.267303,0.202767,0.295060,0.340878,0.223469,1.953880,0.491298,-1.838628,0.903099,-3.177644,2.936882,-1.566523,-4.020634
395,-0.320992,0.075373,-1.591667,0.876455,-0.899993,2.145478,0.231242,0.771361,1.141162,-2.281371,0.287417,-1.491703,2.323088,-2.076305,-4.727710

In [9]:
new_df.to_csv('./data/poly_linear_400.csv', index = False)

In [10]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.1)
    f_quadr = interpolate.interp1d(x, y, kind='quadratic')
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.394290,0.346584,2.283581,-1.559172,0.641352,-2.573262,-0.407517,2.417698,-1.459789,3.592460,-4.019680,0.790601,-1.833108,3.480442,6.263829
1,0.647227,0.814843,1.748575,-1.372752,0.552197,-2.279808,-0.586594,2.769708,-1.421013,3.091121,-3.732280,0.258945,-1.825382,2.735242,5.752893
2,0.867239,1.210315,1.269145,-1.193551,0.463772,-2.005609,-0.735408,3.058585,-1.349328,2.619453,-3.432417,-0.222074,-1.767537,2.043435,5.183572
3,1.054327,1.532999,0.845291,-1.021570,0.376077,-1.750666,-0.853956,3.284329,-1.244734,2.177455,-3.120092,-0.652456,-1.659573,1.405023,4.555866
4,1.208490,1.782896,0.477014,-0.856808,0.289112,-1.514977,-0.942241,3.446940,-1.107230,1.765129,-2.795303,-1.032200,-1.501490,0.820003,3.869775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,1.249635,-0.110651,0.267303,0.202767,0.295060,0.340878,0.223469,1.953880,0.491298,-1.838628,0.903099,-3.177644,2.936882,-1.566523,-4.020634
986,0.698901,-0.048552,-0.391965,0.444175,-0.113244,0.991210,0.240430,1.539669,0.706568,-2.026163,0.714482,-2.610222,2.758144,-1.766645,-4.293635
987,0.044811,0.029961,-1.163660,0.723006,-0.614504,1.736886,0.238922,1.047062,0.981406,-2.199781,0.448990,-1.900194,2.490367,-1.971821,-4.579742
988,-0.712635,0.124889,-2.047781,1.039260,-1.208721,2.577906,0.218946,0.476060,1.315811,-2.359483,0.106626,-1.047561,2.133550,-2.182052,-4.878954
989,-1.573439,0.236233,-3.044328,1.392938,-1.895894,3.514270,0.180501,-0.173337,1.709784,-2.505269,-0.312612,-0.052322,1.687694,-2.397338,-5.191272

In [11]:
new_df.to_csv('./data/poly_linear_1000.csv', index = False)