In [1]:
import pandas as pd
import numpy as np
from scipy import interpolate
import matplotlib.pyplot as plt

In [2]:
data_df = pd.read_csv('C:/Users/chanyoung/Desktop/RBFfitting/data/nonlinear15/non_linear15.csv')

In [3]:
data_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,1.361462,0.868128,1.119836,0.770762,1.543228,-0.484979,1.202227,1.812575,-1.328527,-0.452863,1.329738,1.401647,0.991044,-0.811218,1.467842
1,1.575887,0.502778,1.091785,0.330353,1.899189,-0.116958,0.987593,1.239788,-1.252347,-1.719436,0.306399,0.155447,1.327731,-1.011604,0.255159
2,1.333128,0.269990,1.162955,0.159699,1.646715,1.511054,1.234128,1.932573,-1.371554,-0.929414,0.733253,-1.374973,1.109616,-0.876114,0.516849
3,1.546209,0.297732,1.116530,0.482296,1.882979,-0.754731,0.762650,0.752762,-1.433568,-1.254173,1.054452,0.357797,1.062463,-0.555984,0.641373
4,1.661727,0.587748,1.013359,0.635559,1.464764,-0.546585,1.445773,1.857547,-1.568815,-0.723346,1.086332,1.656669,1.188205,-1.103284,1.055944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-2.679979,-1.521583,0.961226,1.383197,-1.392430,-0.701504,-1.148679,0.558870,-0.177923,0.470893,0.907261,0.241810,-0.787315,-1.079895,1.162237
96,-1.977749,-1.478321,1.206590,0.352901,-0.829146,2.016453,-0.940043,-1.517751,-0.011627,-0.044789,0.697491,1.705942,-1.024586,-0.860960,0.453126
97,-2.235777,-1.149230,1.102117,0.655368,-1.112439,1.523969,-0.893636,-1.060217,0.021164,0.303327,1.165866,0.894137,-0.852924,-0.960449,0.966107
98,-2.246968,-0.699402,1.122137,0.350573,-1.382963,-0.901993,-0.138510,0.038130,-0.155820,0.145202,0.447543,0.029613,-0.210601,-1.063089,-0.596316
99,-1.995263,-1.034104,1.198406,-0.165868,-1.343177,1.984393,-0.326622,0.359332,-0.523444,-1.098315,-0.004930,1.727443,-0.617220,-1.105536,-1.851388

In [4]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.5)
    f_quadr = interpolate.BSpline(x, y, k=2)
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)
new_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,0.125456,1.681278,1.360354,1.970887,-0.207581,1.482972,2.446518,5.202901,-1.833570,5.560184,5.765134,2.702507,-0.623593,0.161115,6.235613
1,0.632704,1.382611,1.259511,1.514646,0.502779,0.564490,1.935677,3.809132,-1.624517,3.127378,3.984545,2.328099,0.030203,-0.232970,4.339195
2,1.025657,1.117085,1.183472,1.125844,1.061031,-0.038994,1.540129,2.731755,-1.464310,1.208720,2.566504,1.882637,0.545299,-0.543086,2.811370
3,1.304314,0.884699,1.132239,0.804481,1.467174,-0.327480,1.259873,1.970772,-1.352950,-0.195789,1.511012,1.366119,0.921693,-0.769233,1.652139
4,1.468674,0.685453,1.105811,0.550557,1.721208,-0.300969,1.094910,1.526182,-1.290437,-1.086149,0.818068,0.778547,1.159388,-0.911411,0.861501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,-2.511467,-1.455419,1.019239,1.168224,-1.299457,-0.104534,-1.071762,0.160195,-0.169261,0.364508,0.939580,0.428923,-0.838218,-1.009097,1.029292
194,-2.328864,-1.499952,1.083908,0.868049,-1.110788,0.657474,-1.044361,-0.479441,-0.094775,0.213052,0.802376,0.973876,-0.905951,-0.970427,0.807682
195,-1.809237,-1.412157,1.264603,0.137928,-0.736173,2.613422,-0.863126,-1.916426,-0.002965,-0.151174,0.729810,1.893055,-1.075488,-0.790162,0.320181
196,-0.952586,-1.192034,1.561325,-1.022140,-0.175612,5.763308,-0.528055,-4.150759,0.106170,-0.728168,0.721881,3.186460,-1.346831,-0.468301,-0.433210
197,0.241089,-0.839583,1.974075,-2.612154,0.570896,10.107132,-0.039149,-7.182441,0.232630,-1.517932,0.778590,4.854092,-1.719977,-0.004844,-1.452491

In [5]:
new_df.to_csv('./data/poly_nonlinear_200.csv', index = False)

In [6]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.25)
    f_quadr = interpolate.BSpline(x, y, k=2)
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)
new_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,0.125456,1.681278,1.360354,1.970887,-0.207581,1.482972,2.446518,5.202901,-1.833570,5.560184,5.765134,2.702507,-0.623593,0.161115,6.235613
1,0.393367,1.527802,1.306832,1.734336,0.166613,0.984356,2.176686,4.466467,-1.722938,4.279512,4.829521,2.524185,-0.279357,-0.046423,5.241329
2,0.632704,1.382611,1.259511,1.514646,0.502779,0.564490,1.935677,3.809132,-1.624517,3.127378,3.984545,2.328099,0.030203,-0.232970,4.339195
3,0.843468,1.245705,1.218391,1.311815,0.800919,0.223373,1.723492,3.230894,-1.538308,2.103780,3.230206,2.114250,0.305089,-0.398524,3.529208
4,1.025657,1.117085,1.183472,1.125844,1.061031,-0.038994,1.540129,2.731755,-1.464310,1.208720,2.566504,1.882637,0.545299,-0.543086,2.811370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,-1.423040,-1.318637,1.398461,-0.388362,-0.479136,4.039122,-0.714820,-2.933924,0.049437,-0.413075,0.717766,2.492979,-1.198434,-0.646931,-0.023278
392,-0.952586,-1.192034,1.561325,-1.022140,-0.175612,5.763308,-0.528055,-4.150759,0.106170,-0.728168,0.721881,3.186460,-1.346831,-0.468301,-0.433210
393,-0.397877,-1.032350,1.753197,-1.763403,0.174399,7.785978,-0.302832,-5.566931,0.167234,-1.096454,0.742156,3.973498,-1.520678,-0.254272,-0.909614
394,0.241089,-0.839583,1.974075,-2.612154,0.570896,10.107132,-0.039149,-7.182441,0.232630,-1.517932,0.778590,4.854092,-1.719977,-0.004844,-1.452491
395,0.964310,-0.613735,2.223959,-3.568391,1.013879,12.726771,0.262991,-8.997288,0.302357,-1.992602,0.831183,5.828242,-1.944727,0.279983,-2.061841

In [7]:
new_df.to_csv('./data/poly_nonlinear_400.csv', index = False)

In [8]:
a = list()
for col in data_df.columns:
    y = data_df[col].values
    x = np.array(list(data_df.index), dtype = float)
    xnew = np.arange(0,99, 0.1)
    f_quadr = interpolate.BSpline(x, y, k=2)
    y_new_quadr = f_quadr(xnew)
    a.append([y_new_quadr])
new_df = pd.DataFrame(np.concatenate(a).T, columns = data_df.columns)
new_df

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,0.125456,1.681278,1.360354,1.970887,-0.207581,1.482972,2.446518,5.202901,-1.833570,5.560184,5.765134,2.702507,-0.623593,0.161115,6.235613
1,0.236049,1.618893,1.338201,1.874243,-0.053340,1.274076,2.335126,4.898836,-1.787852,5.032491,5.380012,2.633310,-0.481737,0.075581,5.826842
2,0.342071,1.557834,1.317040,1.780298,0.094816,1.077779,2.228346,4.607426,-1.744087,4.525364,5.009393,2.561270,-0.345430,-0.006595,5.432814
3,0.443520,1.498101,1.296871,1.689050,0.236888,0.894083,2.126178,4.328672,-1.702277,4.038802,4.653275,2.486389,-0.214671,-0.085412,5.053531
4,0.540398,1.439693,1.277695,1.600499,0.372876,0.722987,2.028622,4.062574,-1.662420,3.572807,4.311659,2.408665,-0.089460,-0.160870,4.688991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,0.241089,-0.839583,1.974075,-2.612154,0.570896,10.107132,-0.039149,-7.182441,0.232630,-1.517932,0.778590,4.854092,-1.719977,-0.004844,-1.452491
986,0.520267,-0.753214,2.070548,-2.981750,0.742511,11.119170,0.077092,-7.884459,0.260001,-1.701417,0.797688,5.232525,-1.806823,0.104839,-1.688254
987,0.812925,-0.661551,2.171662,-3.368545,0.921564,12.178965,0.199487,-8.618371,0.288065,-1.893413,0.819372,5.625927,-1.897741,0.220186,-1.934653
988,1.119065,-0.564595,2.277417,-3.772537,1.108054,13.286517,0.328035,-9.384177,0.316822,-2.093919,0.843641,6.034299,-1.992731,0.341197,-2.191687
989,1.438686,-0.462346,2.387813,-4.193727,1.301983,14.441827,0.462736,-10.181877,0.346272,-2.302936,0.870496,6.457639,-2.091794,0.467871,-2.459357

In [9]:
new_df.to_csv('./data/poly_nonlinear_1000.csv', index = False)